- config/routes.rb
> fixed controller issue

- config/routes.rb
> added quotation missing

- app/models/user.rb
- config/routes.rb
- db/migrate/20200124024153_drop_models.rb
- db/migrate/20200124024334_devise_create_users.rb
- db/schema.rb
- test/fixtures/users.yml
- test/models/user_test.rb
devise model was named different, this changes it to user
> changed devise model name from model to user

- app/views/layouts/application.html.erb
I added a few more things to the navbar
> edited navbar

- Gemfile.lock
- app/controllers/chess_controller.rb
- app/views/chess/index.html.erb
Had to make a slight modification to my Gemfile.lock file as I had an extra line I just removed.  Not sure why this was the case as I had pulled down latest changes but it should now match master exactly.  Added changes to chess_controller.rb that will currently make it possible to see all games for now (even though we don't have any yet) and notes about what I will change once scope task is complete and game.available can be called to list available games.  Also added code to homepage so available games can be listed.
> Add available games list

- app/assets/stylesheets/games.scss
- app/controllers/chess_controller.rb
- app/controllers/games_controller.rb
- app/views/chess/index.html.erb
- app/views/games/show.html.erb
- config/routes.rb
Hello team, I was able create a games #show page to draw out the chess board using only html & css with help from stack overflow. Its currently not linked to the index page so you must typle out  http://localhost:3030/games/show in the browser.  I was left scratching my head when I tried to link this show page to the PLAY NOW! button or arena nav link. I looked at rake routes in my terminal and see game GET #show  path. Don't know what I'm missing here. I will get help from my mentor tonight. If you guys know whats wrong feel free to link this page to our index homepage.
> added chess board on show page & Play now button

- app/controllers/games_controller.rb
- app/models/bishop.rb
- app/models/game.rb
- app/models/king.rb
- app/models/knight.rb
- app/models/pawn.rb
- app/models/piece.rb
- app/models/queen.rb
- app/models/rook.rb
read comments on piece.rb model for more info on isObstructed? method
> Adding is obstruct method

- app/views/games/show.html.erb
> moved destroy button

- app/assets/stylesheets/games.scss
- app/controllers/games_controller.rb
- app/controllers/pieces_controller.rb
- app/views/games/show.html.erb
- config/routes.rb
fixed games.scss, games controller, pieces controller, games show, routes.rb
> fixed files, check art's old branch for files that were changed

- app/models/game.rb
- spec/factories.rb
- spec/helpers/pieces_helper_spec.rb
- spec/helpers/users_helper_spec.rb
- spec/models/piece_spec.rb
- spec/support/factory_girl.rb
fixed factory girl issue, added factories.rb, added passing example tests
> Fixing factorybot

- app/assets/stylesheets/games.scss
- app/controllers/games_controller.rb
- app/models/game.rb
- app/views/games/show.html.erb
changed color back to light brown and dark brown squares
Rendered all pieces on the board based on their position in the database. 
refactored code to use loops .
> Draw pieces

- app/models/king.rb
- spec/factories.rb
- spec/models/king_spec.rb
edited from joe's old add king branch
> King rspec

- spec/models/king_spec.rb
Added valid move tests for the king piece.
> Added valid move tests for king in king_spec.rb

- app/models/knight.rb
- spec/models/knight_spec.rb
basically copied king.rb valid_move? array and changed it to knights movements
> added valid_move? to knight.rb and tested

- app/models/bishop.rb
- spec/models/bishop_spec.rb
- spec/models/rook_spec.rb
bishop movement done, tests done also
fixed up final rook test
> added bishop valid_move? method and test, and fixed rook final test

- app/models/queen.rb
- spec/models/queen_spec.rb
Like a mashup of rook and bishop
> Queen valid

- spec/models/king_spec.rb
Refactored king_spec.rb removing unnecessary code at top and adding tests for king not being able to move off board.
> refactored king_spec.rb

- app/models/game.rb
- app/models/pawn.rb
- app/models/rook.rb
- spec/models/bishop_spec.rb
- spec/models/pawn_spec.rb
- spec/models/piece_spec.rb
all tests are now passing with the reordering of method chain in pawn.rb and with correcting of last test in pawn spec.
> Pawn validmove

- app/controllers/games_controller.rb
- app/views/games/show.html.erb
- config/routes.rb
- db/schema.rb
Added forfeit button to game and it redirects you back to game page and displays message that "Game has been forfeited!"
> Added forfeit button to game

- app/controllers/games_controller.rb
- db/schema.rb
I discovered that if there is an open game, anyone can go in there and DESTROY IT. Fixed the bug now they will not be able to delete and get redirected to home screen.
> non users cannot delete games

- app/controllers/games_controller.rb
bugs still there on login, destroy and edit
> bugs on logins

- app/controllers/games_controller.rb
fixed and tested some bugs, now pretty much cannot do anything unless logged on.
> cannot do anything if not logged in

- app/assets/stylesheets/games.scss
- app/controllers/games_controller.rb
- app/models/game.rb
- app/models/king.rb
- app/models/pawn.rb
- app/views/games/show.html.erb
Take a look at my stalemate file.
> Stalemate file

- app/models/pawn.rb
- spec/models/captured_piece_spec.rb
- spec/models/pawn_spec.rb
created a simple code for pawn promotion under pawn.rb
if the pawn makes it to a certain axis, it can get promoted
after this, there will be javascript added to ask what piece it wants to get promoted to
> Pawn promo

- app/controllers/games_controller.rb
- app/models/king.rb
> fixed games#show and kingrb

- app/models/piece.rb
check method finally works, method 'is_in_check?' is called for this to work. in piece.rb
> check finally works

- app/models/pawn.rb
- app/models/piece.rb
> finished en-passant

- app/controllers/pieces_controller.rb
- app/helpers/games_helper.rb
- app/models/piece.rb
- app/views/games/_player_one.html.erb
- app/views/games/_player_two.html.erb
- config/routes.rb
castling works! feel free to change up the css on the button, i left it normal.
> added castling logic

- app/controllers/games_controller.rb
Fixed issue/bug so that when a 2nd player joins a game player 1's game page is refreshed so they see a 2nd player has joined and game is ready to play.
> Added code to fix bug so player 1's screen is refreshed when 2nd player joins game

- app/controllers/games_controller.rb
- app/controllers/pieces_controller.rb
- app/controllers/users_controller.rb
- app/models/game.rb
- app/models/piece.rb
- app/views/games/show.html.erb
- db/migrate/20200310024142_drop_black_white_from_users.rb
- db/schema.rb
- spec/models/game_spec.rb
> adding checkmate logic, game state over

- app/assets/stylesheets/master.scss
- app/controllers/games_controller.rb
- app/views/games/show.html.erb
Fixed issue where when one player destroys a game the other player would receive no notification game was over and had been destroyed by opponent.  Now other player will be notified game was destroyed by opponent.
> Resolved issue where selecting destroy this game notification issue

- app/views/games/show.html.erb
Changed code so that forfeit button is hidden until two players have joined game.
> hid one player forfeit option

- app/controllers/games_controller.rb
- app/models/game.rb
added validation to game model and fixed games controller to reflect change.
> made it so games without a name cant be created

- app/views/chess/index.html.erb
> fixing issue 123, removed available games for unregistered users
